language: node_js
env:
  - NODE_OPTIONS=--max_old_space_size=4096
node_js:
  - '10'
sudo: false
install:
  - yarn
script:
  - yarn lint
  - yarn build
deploy:
  - provider: firebase
    on: master
    skip_cleanup: true
    token:
      secure: uH5KRGo89UelknWIRg6zYu1QSfXq9rnfojZwUa7qZrB3iEWEd1jWYpa95kIQu7AR0salUg9/zj7l6rcnXIA88u0jAvsp6F8h4yGhbDi+iDLy1qUZ4AiFzYip5ceZQdzgPkj+NnRF3kFRGInuHpvjoelFkjRkligVDJNUACqC0lQ7W61Gn5F3psKjRPWc409SxMV81lFgqeRU5qBKB5ta9rjx1OGefHPDVrCR+PxVvkogSGaEXPT6r/G1b42O2ngpLW172gAmZ0/yXlBDPZktgb6cGstxm2HX7ibZWxRX8TDClX7MyNWubwoUSn5x4l/PsJKbL9h9STULANQOVtKST6qkKqfwJVJGrQ9gEw4R01rHkD2usNWEi9GEgWkxVVBSfiNnDf8Ay/xGMNhEbeJhN0Xjgwg3gvLmdId8f5NpMB5QZNIfcdCqoJkBNt3lh2Vnfgc9bpa8fFEJVjTjbP3PIZ/UYyGix53XQCJIRO9UhJeehBbttRlwpgpumxNB5x+hUfvRGSln5ay7Kw92ko7Vh0dIIzW537finIoLg866Ps0zuRcv4bziCgbujfZRCg9DUAAC5jv4UY+Rf5sDSU+aK3AVjfjoqQeAt9xeSj1/pKm9YRAj8EEl5U8OyHOvAvL1Dtpkxyt2yHN8Oc7o7drR2pEQ1DJRW4+CJar2CCdfOwA=
  - provider: firebase
    on: ts
    skip_cleanup: true
    project: digital-twin-explorer-ts
    token:
      secure: ibcXvFxDnX0J6dRx++nj/Ka951m80RpC+iAxDC0EOKMHY4ZjkEssUA7DoRTG/U2hVPYZDeoiQbdtzxU8BTzaRyQBucvy6xDhwTtas3fr6Ft7sxdx5gVzK2qvotYvsaB0DL6LyWtOAVl9oirC6kD1X11cotgyEN9VSkf2lroLhIizJe2Nb679eX28aG2kPyZpsmFvMKzMwGLSw1Y2arjWV7FT4iYFRc8XCpnz4OLjhYQrkgsyzrDSPUzzr47ez0VwFbJDl0wqFx3ldLU3GBbVJhI7Aka/2ke5T+t4oLCoyGG0VWEDbGd7aB7NLy7gVNaxRihxdBisiXBDiS5x/wFF73FV52iXKILNjVMgt7U/YAswElSYlGOyaMzvx51R+/GltmBVJYV/O9pifYb/CwWIz8PzNSlrHTAa7oEPbpbpAnHFTC1ViIlAdTv1Up1UIs96hRjeV5W7aAPPQUsmGefXFG5CrpRbWRz5+EdVBu+q2wHdYyDh9k822mWH9SEEpNc5W70bFo48gC19S9A+YB1K2ce/E6AbVlps8AOSpPprv/FjkFzw1+J+TLtJXG31B57OBvvRW9R9aRZsJCvQnzSDf+VWBojlbzWVFuPQHtYrSrDMFPKFga3soHQTLBEGupLULSWlOpzyKoypmBPfW39DodaxyzoroeYWcBS3N0ouMXk=
